query GET_PAYOUT_REPORTS {
  listPayoutReport {
    data {
      sellerId
      paymentMethod
      creationDate
      timeZone
      transactionType
      grossCurrency
      grossDebit
      grossCredit
      exchangeRate
      netCurrency
      netDebit
      netCredit
      commissionAmount
      orderId
      payId
      invoiceId
      chargebackType
      reserved1
      reserved2
    }
    paging {
      total
      pages
      currentPage
      perPage
    }
  }
}
